defaultIndent: "  "
modifyLineBreaks:
  preserveBlankLines: 1
lookForAlignDelims:
  tikzcd:
    delims: 1
    alignDoubleBackSlash: 1
specialBeginEnd:
  tikzpicture:
    begin: '\\begin\{tikzpicture\}'
    end: '\\end\{tikzpicture\}'
    lookForThis: 1
