version: 1
tabs:
  - C:\Users\mayas\GitHub\Problem-Catalogue-LateX-\document.tex
active: C:\Users\mayas\GitHub\Problem-Catalogue-LateX-\document.tex
cursors:
  - path: C:\Users\mayas\GitHub\Problem-Catalogue-LateX-\document.tex
    line: 1
    column: 1
